### ISSUE TITLE
[model request][might not related here]

### ISSUE THREAD

**Issue by FNsi** [Kim2091/kim-chaiNNer-Templates#2]
May you train the 2x clear reality model? 

(I saw your 2x Anifilm Compact based on a private model by @eula 5600x 3070 named 4x_eula_anifilm_v1_225k, their output are close)

**Comment by Kim2091** [comment]
@FNsi ClearReality was very difficult to train, I doubt I'll be retraining it any time soon (especially in 2x). I will ping you here though if I do

**Comment by FNsi** [comment]
@Kim2091 Hi, I interpolated the clear reality and clear reality soft 50-50, turns out it looks even better to handle more complex situations!

**Comment by FNsi** [comment]
Did you try with synthetic data? 

Somehow currently, with multi model, some decent results are possible.
